import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { supabase } from '../utils/supabase'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>amarjeet assignment</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to roringo challenge
        </h1>

      </main>
    </div>
  )
}
  export async function getStaticProps(context){
    const data = await supabase.from('profile').select('*');
    return {
      props: {data:data},
    };
  }

